import { db } from '../../../shared/db'; // FIXED PATH
import { ttsService } from './TTSService'; // FIXED PATH (same folder)
import { storage } from '../../../shared/services/storage';
import { logger } from '../../../shared/services/Logger';

export const AudioGenerationService = {
    async generate(chunkId: number): Promise<void> {
        const chunk = await db.chunks.get(chunkId);
        if (!chunk || chunk.status === 'processing') return;

        const project = await db.projects.get(chunk.projectId);
        if (!project) return;

        await db.chunks.update(chunkId, { status: 'processing' });

        try {
            const voiceId = chunk.voiceOverride?.voiceId || project.voiceSettings?.voiceId || 'af_heart';
            const speed = chunk.voiceOverride?.speed || project.voiceSettings?.speed || 1.0;
            const config = { voice: voiceId, speed: speed, lang: 'en-us' };
            const filePath = `audio/${chunk.cleanTextHash}.wav`;

            const cached = await db.audioCache.get(chunk.cleanTextHash);
            if (cached && await storage.exists(cached.path)) {
                await db.chunks.update(chunkId, { 
                    status: 'generated',
                    generatedFilePath: cached.path 
                });
                return;
            }

            // Capture results including the NEW peaks generated by the worker
            const result = await ttsService.generate(chunk.textContent, config, filePath);

            await db.audioCache.put({
                hash: chunk.cleanTextHash,
                path: filePath,
                byteSize: result.byteSize,
                mimeType: 'audio/wav',
                createdAt: new Date()
            });

            await db.chunks.update(chunkId, { 
                status: 'generated',
                generatedFilePath: filePath,
                waveformPeaks: result.peaks // Persist peaks to Chunk for Canvas rendering
            });

        } catch (error) {
            logger.error('AudioGen', `Failed synthesis for chunk ${chunkId}`, error);
            await db.chunks.update(chunkId, { status: 'failed_tts' });
        }
    }
};